"""Dependency-free SVG and CSV figures for GLEE validation reports."""

from __future__ import annotations

import csv
import hashlib
import io
import math
from html import escape
from pathlib import Path
from typing import Any, Iterable, Sequence


BLUE = "#0072B2"
ORANGE = "#D55E00"
GREEN = "#009E73"
PURPLE = "#CC79A7"
SKY = "#56B4E9"
GREY = "#6B7280"
LIGHT_GREY = "#E5E7EB"
DARK = "#111827"
MODEL_COLORS = {
    "hierarchical_program": BLUE,
    "opponent_program": GREEN,
    "population_program": PURPLE,
    "recency_kernel": SKY,
    "regularized_tabular": ORANGE,
    "unconditional_empirical": GREY,
}


def _atomic_text(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(value, encoding="utf-8")
    temporary.replace(path)


def _sha_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _write_csv(path: Path, fieldnames: Sequence[str], rows: Iterable[dict[str, object]]) -> None:
    stream = io.StringIO()
    writer = csv.DictWriter(stream, fieldnames=fieldnames, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    _atomic_text(path, stream.getvalue())


def _format_tick(value: float) -> str:
    if abs(value) >= 10:
        return f"{value:.0f}"
    if abs(value) >= 1:
        return f"{value:.1f}"
    return f"{value:.2f}"


def _domain(values: Sequence[float], *, include_zero: bool = False, unit: bool = False) -> tuple[float, float]:
    if unit:
        return 0.0, 1.0
    selected = list(values)
    if include_zero:
        selected.append(0.0)
    if not selected:
        return 0.0, 1.0
    low, high = min(selected), max(selected)
    if math.isclose(low, high):
        padding = max(0.1, abs(low) * 0.2)
    else:
        padding = (high - low) * 0.08
    return low - padding, high + padding


class Svg:
    """Minimal SVG canvas with stable paper-oriented styling."""

    def __init__(self, *, width: int = 960, height: int = 600, title: str) -> None:
        self.width = width
        self.height = height
        self.title = title
        self.elements = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">',
            f'<title id="title">{escape(title)}</title>',
            '<desc id="desc">Generated by bargaining-validation-v1 from causally prior predictions.</desc>',
            f'<rect x="0" y="0" width="{width}" height="{height}" fill="#FFFFFF"/>',
            '<style>text{font-family:Inter,Segoe UI,Arial,sans-serif;fill:#111827}.title{font-size:22px;font-weight:600}.label{font-size:14px}.tick{font-size:12px;fill:#4B5563}.legend{font-size:12px}.axis{stroke:#374151;stroke-width:1.2}.grid{stroke:#E5E7EB;stroke-width:1}.zero{stroke:#111827;stroke-width:1.3}.ideal{stroke:#9CA3AF;stroke-width:1.5;stroke-dasharray:7 6}</style>',
        ]

    def line(self, x1: float, y1: float, x2: float, y2: float, *, stroke: str = DARK, width: float = 1.0, css: str | None = None, dash: str | None = None) -> None:
        attributes = f' class="{css}"' if css else f' stroke="{stroke}" stroke-width="{width}"'
        if dash:
            attributes += f' stroke-dasharray="{dash}"'
        self.elements.append(f'<line x1="{x1:.2f}" y1="{y1:.2f}" x2="{x2:.2f}" y2="{y2:.2f}"{attributes}/>')

    def rect(self, x: float, y: float, width: float, height: float, *, fill: str, stroke: str | None = None, opacity: float = 1.0) -> None:
        border = f' stroke="{stroke}"' if stroke else ""
        self.elements.append(f'<rect x="{x:.2f}" y="{y:.2f}" width="{max(0.0, width):.2f}" height="{max(0.0, height):.2f}" fill="{fill}" opacity="{opacity:.3f}"{border}/>')

    def circle(self, x: float, y: float, radius: float, *, fill: str, opacity: float = 1.0, stroke: str | None = None) -> None:
        border = f' stroke="{stroke}" stroke-width="1"' if stroke else ""
        self.elements.append(f'<circle cx="{x:.2f}" cy="{y:.2f}" r="{radius:.2f}" fill="{fill}" opacity="{opacity:.3f}"{border}/>')

    def polyline(self, points: Sequence[tuple[float, float]], *, stroke: str, width: float = 2.2) -> None:
        if len(points) < 2:
            return
        serialized = " ".join(f"{x:.2f},{y:.2f}" for x, y in points)
        self.elements.append(f'<polyline points="{serialized}" fill="none" stroke="{stroke}" stroke-width="{width}" stroke-linejoin="round" stroke-linecap="round"/>')

    def text(self, x: float, y: float, value: object, *, css: str = "label", anchor: str = "start", rotate: float | None = None, fill: str | None = None) -> None:
        transform = f' transform="rotate({rotate:.1f} {x:.2f} {y:.2f})"' if rotate is not None else ""
        color = f' fill="{fill}"' if fill else ""
        self.elements.append(f'<text x="{x:.2f}" y="{y:.2f}" class="{css}" text-anchor="{anchor}"{transform}{color}>{escape(str(value))}</text>')

    def finish(self) -> str:
        self.elements.append("</svg>")
        return "\n".join(self.elements) + "\n"


def _axes(svg: Svg, *, left: float, top: float, right: float, bottom: float, x_domain: tuple[float, float], y_domain: tuple[float, float], x_label: str, y_label: str, x_ticks: int = 5, y_ticks: int = 5) -> tuple[Any, Any]:
    x_low, x_high = x_domain
    y_low, y_high = y_domain

    def x(value: float) -> float:
        return left + (value - x_low) / (x_high - x_low) * (right - left)

    def y(value: float) -> float:
        return bottom - (value - y_low) / (y_high - y_low) * (bottom - top)

    for index in range(x_ticks + 1):
        value = x_low + (x_high - x_low) * index / x_ticks
        coordinate = x(value)
        svg.line(coordinate, top, coordinate, bottom, css="grid")
        svg.text(coordinate, bottom + 22, _format_tick(value), css="tick", anchor="middle")
    for index in range(y_ticks + 1):
        value = y_low + (y_high - y_low) * index / y_ticks
        coordinate = y(value)
        svg.line(left, coordinate, right, coordinate, css="grid")
        svg.text(left - 10, coordinate + 4, _format_tick(value), css="tick", anchor="end")
    svg.line(left, top, left, bottom, css="axis")
    svg.line(left, bottom, right, bottom, css="axis")
    svg.text((left + right) / 2, svg.height - 18, x_label, anchor="middle")
    svg.text(22, (top + bottom) / 2, y_label, anchor="middle", rotate=-90)
    return x, y


def _horizontal_delta(path: Path, csv_path: Path, *, title: str, metric_label: str, rows: Sequence[dict[str, object]]) -> None:
    selected = sorted(rows, key=lambda row: float(row["delta"]))
    values = [float(row["delta"]) for row in selected]
    low, high = _domain(values, include_zero=True)
    width = 960
    height = max(520, 120 + 30 * len(selected))
    svg = Svg(width=width, height=height, title=title)
    svg.text(30, 38, title, css="title")
    left, right, top, bottom = 190.0, width - 35.0, 70.0, height - 65.0

    def x(value: float) -> float:
        return left + (value - low) / (high - low) * (right - left)

    for index in range(6):
        value = low + (high - low) * index / 5
        coordinate = x(value)
        svg.line(coordinate, top, coordinate, bottom, css="grid")
        svg.text(coordinate, bottom + 22, _format_tick(value), css="tick", anchor="middle")
    zero = x(0.0)
    svg.line(zero, top, zero, bottom, css="zero")
    band = (bottom - top) / max(1, len(selected))
    for index, row in enumerate(selected):
        value = float(row["delta"])
        center = top + band * (index + 0.5)
        start = min(zero, x(value))
        color = BLUE if value <= 0 else ORANGE
        svg.rect(start, center - min(8.0, band * 0.32), abs(x(value) - zero), min(16.0, band * 0.64), fill=color, opacity=0.9)
        svg.text(left - 10, center + 4, row["opponent"], css="tick", anchor="end")
    svg.line(left, bottom, right, bottom, css="axis")
    svg.text((left + right) / 2, height - 18, metric_label, anchor="middle")
    svg.text(right - 4, 55, "negative = hierarchical program better", css="tick", anchor="end")
    _atomic_text(path, svg.finish())
    _write_csv(csv_path, ("opponent", "delta"), selected)


def _calibration_figure(path: Path, csv_path: Path, evaluation: dict[str, Any]) -> None:
    title = "Response probability calibration"
    svg = Svg(title=title)
    svg.text(30, 38, title, css="title")
    x, y = _axes(svg, left=85, top=70, right=910, bottom=520, x_domain=(0, 1), y_domain=(0, 1), x_label="Mean predicted acceptance probability", y_label="Observed acceptance frequency")
    svg.line(x(0), y(0), x(1), y(1), css="ideal")
    models = ("hierarchical_program", "regularized_tabular", "recency_kernel", "opponent_program")
    csv_rows: list[dict[str, object]] = []
    for model_index, model in enumerate(models):
        points = []
        for bucket in evaluation["response_calibration"][model]:
            if int(bucket["count"]) == 0:
                continue
            predicted = float(bucket["mean_prediction"])
            observed = float(bucket["observed_frequency"])
            points.append((x(predicted), y(observed)))
            svg.circle(x(predicted), y(observed), min(7.0, 3.0 + math.sqrt(int(bucket["count"]))), fill=MODEL_COLORS[model], opacity=0.85, stroke="#FFFFFF")
            csv_rows.append({"model": model, **bucket})
        svg.polyline(points, stroke=MODEL_COLORS[model])
        legend_x = 100 + model_index * 205
        svg.line(legend_x, 56, legend_x + 22, 56, stroke=MODEL_COLORS[model], width=3)
        svg.text(legend_x + 28, 60, model.replace("_", " "), css="legend")
    _atomic_text(path, svg.finish())
    _write_csv(csv_path, ("model", "bin", "lower", "upper", "count", "mean_prediction", "observed_frequency"), csv_rows)


def _proposal_scatter(path: Path, csv_path: Path, records: Sequence[dict[str, Any]]) -> None:
    title = "Observed and predicted opponent proposal shares"
    svg = Svg(title=title)
    svg.text(30, 38, title, css="title")
    x, y = _axes(svg, left=85, top=70, right=910, bottom=520, x_domain=(0, 1), y_domain=(0, 1), x_label="Observed opponent share", y_label="Predicted opponent share")
    svg.line(x(0), y(0), x(1), y(1), css="ideal")
    selected = [record for record in records if record["action_type"] == "proposal"]
    csv_rows = []
    for record in selected:
        observed = float(record["actual"]["proposal_share"])
        hierarchical = float(record["predictions"]["hierarchical_program"]["mean"])
        tabular = float(record["predictions"]["regularized_tabular"]["mean"])
        svg.circle(x(observed), y(tabular), 2.6, fill=ORANGE, opacity=0.35)
        svg.circle(x(observed), y(hierarchical), 3.2, fill=BLUE, opacity=0.55)
        csv_rows.append({"game_id": record["game_id"], "opponent": record["opponent"]["name"], "observed": observed, "hierarchical_program": hierarchical, "regularized_tabular": tabular})
    svg.circle(116, 56, 4, fill=BLUE)
    svg.text(128, 60, "hierarchical program", css="legend")
    svg.circle(305, 56, 4, fill=ORANGE)
    svg.text(317, 60, "regularized tabular", css="legend")
    _atomic_text(path, svg.finish())
    _write_csv(csv_path, ("game_id", "opponent", "observed", "hierarchical_program", "regularized_tabular"), csv_rows)


def _entropy_figure(path: Path, csv_path: Path, evaluation: dict[str, Any]) -> None:
    title = "Program-posterior entropy during opponent adaptation"
    rows = evaluation["entropy_by_prior_games"]
    x_values = [float(row["prior_target_game_count"]) for row in rows]
    svg = Svg(title=title)
    svg.text(30, 38, title, css="title")
    x_domain = _domain(x_values, include_zero=True)
    x, y = _axes(svg, left=85, top=70, right=910, bottom=520, x_domain=x_domain, y_domain=(0, 1), x_label="Causally prior target games", y_label="Normalized posterior entropy")
    series = (("response_entropy", BLUE, "response programs"), ("proposal_entropy", GREEN, "proposal programs"))
    for index, (field, color, label) in enumerate(series):
        points = [(x(float(row["prior_target_game_count"])), y(float(row[field]))) for row in rows if row[field] is not None]
        svg.polyline(points, stroke=color)
        for point_x, point_y in points:
            svg.circle(point_x, point_y, 3.2, fill=color)
        legend_x = 110 + index * 220
        svg.line(legend_x, 56, legend_x + 22, 56, stroke=color, width=3)
        svg.text(legend_x + 28, 60, label, css="legend")
    _atomic_text(path, svg.finish())
    _write_csv(csv_path, ("prior_target_game_count", "origin_count", "response_entropy", "proposal_entropy"), rows)


def _surprise_figure(path: Path, csv_path: Path, evaluation: dict[str, Any]) -> None:
    title = "Rolling predictive surprise"
    rows = evaluation["surprise_series"]
    x_values = [float(row["decision_index"]) for row in rows]
    y_values = [float(row[field]) for row in rows for field in ("response_rolling_nll", "proposal_rolling_nll") if row[field] is not None]
    svg = Svg(title=title)
    svg.text(30, 38, title, css="title")
    x, y = _axes(svg, left=85, top=70, right=910, bottom=520, x_domain=_domain(x_values, include_zero=True), y_domain=_domain(y_values), x_label="Rolling-origin decision index", y_label="Mean negative log likelihood")
    series = (("response_rolling_nll", BLUE, "response"), ("proposal_rolling_nll", PURPLE, "proposal"))
    for index, (field, color, label) in enumerate(series):
        points = [(x(float(row["decision_index"])), y(float(row[field]))) for row in rows if row[field] is not None]
        svg.polyline(points, stroke=color, width=1.8)
        legend_x = 110 + index * 170
        svg.line(legend_x, 56, legend_x + 22, 56, stroke=color, width=3)
        svg.text(legend_x + 28, 60, label, css="legend")
    _atomic_text(path, svg.finish())
    _write_csv(csv_path, ("decision_index", "completed_at", "response_rolling_nll", "proposal_rolling_nll", "response_window_count", "proposal_window_count"), rows)


def write_validation_figures(*, evaluation: dict[str, Any], diagnostics: dict[str, Any], records: Sequence[dict[str, Any]], output_dir: Path) -> list[dict[str, object]]:
    """Write 6 scalable figures plus their exact source tables."""
    output_dir.mkdir(parents=True, exist_ok=True)
    response_rows = []
    proposal_rows = []
    for opponent in diagnostics["opponents"]:
        response_delta = opponent["program_vs_tabular"]["response_nll_delta"]
        proposal_delta = opponent["program_vs_tabular"]["proposal_mae_delta"]
        if response_delta is not None:
            response_rows.append({"opponent": opponent["opponent"]["name"], "delta": response_delta})
        if proposal_delta is not None:
            proposal_rows.append({"opponent": opponent["opponent"]["name"], "delta": proposal_delta})
    figure_specs = [
        ("01-response-nll-delta.svg", "01-response-nll-delta.csv", lambda svg, csv_path: _horizontal_delta(svg, csv_path, title="Per-opponent response prediction", metric_label="Hierarchical minus regularized-tabular NLL", rows=response_rows)),
        ("02-proposal-mae-delta.svg", "02-proposal-mae-delta.csv", lambda svg, csv_path: _horizontal_delta(svg, csv_path, title="Per-opponent proposal prediction", metric_label="Hierarchical minus regularized-tabular MAE", rows=proposal_rows)),
        ("03-response-calibration.svg", "03-response-calibration.csv", lambda svg, csv_path: _calibration_figure(svg, csv_path, evaluation)),
        ("04-proposal-observed-predicted.svg", "04-proposal-observed-predicted.csv", lambda svg, csv_path: _proposal_scatter(svg, csv_path, records)),
        ("05-posterior-entropy.svg", "05-posterior-entropy.csv", lambda svg, csv_path: _entropy_figure(svg, csv_path, evaluation)),
        ("06-predictive-surprise.svg", "06-predictive-surprise.csv", lambda svg, csv_path: _surprise_figure(svg, csv_path, evaluation)),
    ]
    result = []
    for svg_name, csv_name, writer in figure_specs:
        svg_path = output_dir / svg_name
        csv_path = output_dir / csv_name
        writer(svg_path, csv_path)
        result.append(
            {
                "svg": svg_name,
                "svg_sha256": _sha_file(svg_path),
                "svg_bytes": svg_path.stat().st_size,
                "data": csv_name,
                "data_sha256": _sha_file(csv_path),
                "data_bytes": csv_path.stat().st_size,
            }
        )
    return result
